name: eshhtikiyl_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  image_picker: ^1.2.1
  uuid: ^4.5.2
  awesome_snackbar_content: ^0.1.8
  http: ^1.6.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  permission_handler: ^12.0.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_auth: ^6.1.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  responsive_framework: ^1.5.1
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
