name: eshhtikiyl_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  image_picker: ^1.2.1
  uuid: ^4.5.2
  awesome_snackbar_content: ^0.1.8
  http: ^1.6.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.0.3
  firebase_auth: ^5.1.4
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
